### ISSUE TITLE
Wait cursor when saving files in Visual Studio 2017

### ISSUE THREAD

**Issue by JRosanowski** [sboulema/TSVN#12]
We have a reasonable sized project and when the extension is enabled there a wait cursor appears for about 2 seconds every time we save a file.

**Comment by sboulema** [comment]
Every time a file is saved the Pending Changes window is updated. This means calling 'svn status' on your repo and looping over the changes. 
How long does it take to call 'svn status' from the commandline  and how many pending changes do you have?

**Comment by JRosanowski** [comment]
svn status from the command line is quick. There's no pending changes.

**Comment by sboulema** [comment]
Can you try this custom version which has the Pending Changes hook on saving files disabled. Does that remove the 2 sec delay ?

[TSVN_3.2_custom.vsix.zip](https://github.com/sboulema/TSVN/files/615699/TSVN_3.2_custom.vsix.zip)

**Comment by JRosanowski** [comment]
Yes, with that version the wait cursor is gone.

**Comment by sboulema** [comment]
Cool, thanks for testing! I will look into it, maybe something changed in the way to start new processes from a vs extension...
