### ISSUE TITLE
Extension breaks for some svn ignore values.

### ISSUE THREAD

**Issue by JRosanowski** [sboulema/TSVN#13]
If I add '*.user' to tortoise svn ignores then an exception appears in the Pending Changes window.

**Comment by sboulema** [comment]
Can you provide a bit more info?

- What kind of exception
- Screenshots
- Steps to reproduce

Tried to reproduce it but was unable to get any exception

**Comment by JRosanowski** [comment]
![properties](https://cloud.githubusercontent.com/assets/14955434/20578014/fe2aa98c-b229-11e6-8dca-7906bab8f07b.png)
![exception](https://cloud.githubusercontent.com/assets/14955434/20578018/04a8242e-b22a-11e6-88ad-2d3289dc09dc.png)

Here's a snap of the properties and the exception. I added *.crp as an ignore on the root folder of the svn checkout.

**Comment by sboulema** [comment]
Found it! Will be fixed in the next version.
