### ISSUE TITLE
Enhancement - add ability to hide unversioned files and folders.

### ISSUE THREAD

**Issue by JRosanowski** [sboulema/TSVN#14]
Apologies if there's a setting for this. Would be good to be able to hide unversioned files or folders in the Pending Changes window, maybe with a button beside the "Commit" and "Revert" buttons. For eg when you link a file to a project directory in Visual Studio then you end up with a folder created in that project directory, this shows up as an unversioned file in the Pending Changes window but we'd never want to check it in. In our project we have iOS, Android, and Windows links to files in multiple folders so the Pending Changes window ends up filled with unversioned folders.

**Comment by sboulema** [comment]
Good suggestion! Will be in the next version :)
