### ISSUE TITLE
Extension 'TSVN' requires a version of the .net framework that is not installed, but doesn't indicate which one is needed

### ISSUE THREAD

**Issue by Shawn1874** [sboulema/TSVN#15]
![2016-12-08 14_04_21-extensions and updates](https://cloud.githubusercontent.com/assets/18298395/21029605/68f969ee-bd4f-11e6-963a-efe1955e8ff6.png)

It's not clear which version of the framework I need.  I can't find any documentation that specifies that, nor does the error message tell me.  I have the following frameworks installed:
.Net 1.1, .NET 4.5, .Net 4.6.1

EDIT - I forgot to mention that I am trying to install the extension from within Visual Studio Ultimate 2013.  If I just need to install a different .net version for now, I can probably manually download it for now.  I just need to know which one I need.

**Comment by sboulema** [comment]
Probably related to this: https://github.com/paulcbetts/SaveAllTheTime/issues/39
Will make a test version with a possible fix tomorrow :)

**Comment by Shawn1874** [comment]
Thank you.  That worked!

**Comment by sboulema** [comment]
Fixed in v3.3 :D
