### ISSUE TITLE
VS 2017 RC.4 support

### ISSUE THREAD

**Issue by DesertDragon** [sboulema/TSVN#17]
Don't install on VS 2017 RC.4 (26606).
08.02.17 16:17:43 - Version value mismatch. VsixManifest value: '3.2'; Catalog manifest value: '3.1'; Package manifest value: '3.1'
08.02.17 16:17:43 - Install Error : System.InvalidOperationException: The value of property 'Version' is not consistent amongst all manifests.

**Comment by sboulema** [comment]
Can you please verify that this new version fixes the problem. 

[TSVN_3.4.4.vsix.zip](https://github.com/sboulema/TSVN/files/760400/TSVN_3.4.4.vsix.zip)

**Comment by DesertDragon** [comment]
This version does install without error.
