### ISSUE TITLE
Main menu doesn't work if projects are under revision and not the solution

### ISSUE THREAD

**Issue by antonioriva** [sboulema/TSVN#18]
I have a scenario where projects are under revision and the solution has only an utility/build project with all other project loaded... This is not under revisione.

Se solution to this problem may be consider the current project if .svn folder is not found into the solution folder...

Also having TSVN menu in project contextual menu can help. Now I can mke operation over a single revisioned file (with contectual menu) but not over a project.

**Comment by sboulema** [comment]
Added in the next release!
