### ISSUE TITLE
Can not Locate solution correctly v3.5.8

### ISSUE THREAD

**Issue by sharksangels** [sboulema/TSVN#20]
Versions
VS : 2017 Conmmunity
TSVN : 3.5.8

Update and Commit can not locate solution correctly.
My solution dir is W:/MySolution, and Update and Commit are working at D:/svn/MySolution.
Is there a way to set it correctly or it is a bug of new version?

**Comment by sharksangels** [comment]
I rollbacked to v3.4.4 and it works fine, this should be a bug of new version i posted above.

**Comment by sboulema** [comment]
Sorry! Should be fixed in the new 3.6 release
