### ISSUE TITLE
Compare wrong local path

### ISSUE THREAD

**Issue by mario-bless** [sboulema/TSVN#21]
Hi there

first, I would like to thank for the great tool. 
With Version 3.6.10 TSVN does not work as it used to work anymore. It seems it can't resolve properly the local repository and hence it can't compare, update, etc. anymore... 
I did reinstall it - however did not help at all...

thank for your support

Mario

**Comment by sboulema** [comment]
Can you please tell me more on your repository and local folder structure?
What path are you expecting and what path is TSVN using?
Any errors?
What is the output of `svn info` on the command line inside your repository?

**Comment by mario-bless** [comment]
Hi Samir

attached you find how it looks like when I do "SVN check for modification" from the explorer - an how it looks if I select <Tsvn><Show Changes>. Until yesterday it worked well, but since today (I guess automatic update) it shows as local repository to c:\svn\trunk\trunk
![vs2015](https://cloud.githubusercontent.com/assets/26087498/24462808/47877708-14a5-11e7-9bb6-b4bd0d755440.png)

![explorer](https://cloud.githubusercontent.com/assets/26087498/24462665/dc068140-14a4-11e7-9571-683135402a3f.png)

**Comment by sboulema** [comment]
Thanks for the info!

Can you please try this version: https://github.com/sboulema/TSVN/releases/tag/v3.6.11

**Comment by andremoellerbr** [comment]
Same issue here. V3.6.11 fixed it.
Thanks

**Comment by mario-bless** [comment]
Hi Samir

Yes, it works fine, thanks for the fast fixing...

Ciao for now
