### ISSUE TITLE
Non of the main menu items execute... is there a setting?

### ISSUE THREAD

**Issue by pertheli** [sboulema/TSVN#22]
Using 3.7.12: in VS2015
When clicking on any of the main menu items like Show Log... Branch... nothing happens.
However clicking the popup menu items for the individual file like Blame... is working properly.
Is there any setting to set?

**Comment by sboulema** [comment]
Did you install TortoiseSVN with the client tools? https://i.stack.imgur.com/31I6E.jpg

**Comment by pertheli** [comment]
oh my! thanks for the detail info! its working!
