### ISSUE TITLE
Support for lightweight solution load

### ISSUE THREAD

**Issue by FrecherxDachs** [sboulema/TSVN#26]
If you enable lightweight solution load in Visual Studio 2017 and you are in any code editor of an unloaded project, using one of the TSVN shortcuts will lead to an error message. The only way to get around this, is to load the project before, then it works as expected.

I guess the used APIs need to be updated to work with lightweight solutions.

**Comment by sboulema** [comment]
Thanks for reporting! Should be fixed in the new release.
