### ISSUE TITLE
Pending changes only uses the folder icon

### ISSUE THREAD

**Issue by Sacryn** [sboulema/TSVN#27]
Using Visual Studio 2015. And the pending changes window lists all entries with a folder icon. Which is confusing. Would prefer it if each entry used the associated icon (i.e. same as the normal solution explorer does).

**Comment by sboulema** [comment]
Thanks for reporting this bug, it should now be fixed in the new release!

I am not very proud of that pending changes window :p 
It could surely use a proper refactor...

**Comment by Sacryn** [comment]
Indeed.. Would be awesome if you could click items in the list to bring up the diff-view as well.

As to the initial bug, its solved in the latest version.

**Comment by sboulema** [comment]
Good suggestion, moved that to #29 !

Will look into it :)
