### ISSUE TITLE
SVN Add Functionality.

### ISSUE THREAD

**Issue by hafeefshaik** [sboulema/TSVN#28]
Whenever we add new file to the project or solution, SVN is not able to add that file to repository. Is this enhancement is possible?

**Comment by sboulema** [comment]
Added as an option in the new 4.3.23 release!

**Comment by hafeefshaik** [comment]
Thanks @sboulema , Will test and provide you feedback.

**Comment by hafeefshaik** [comment]
Its working as expected, Thanks again @sboulema . Your are doing wonderful job.
