### ISSUE TITLE
TSVN form context menu.

### ISSUE THREAD

**Issue by hafeefshaik** [sboulema/TSVN#30]
When I right click on the folder, solution or project, system should allow me to perform all SVN action like commit, add or delete. Scope is important, for instance , right clicked on a folder to commit the changes, it should bring the dialog box and files related to that specific folder.

**Comment by sboulema** [comment]
Which context menu are we talking about?

The one in the solution explorer (TSVN actions are available for files and projects, not for folders and solution), or the context menu in the Pending Changes window?

**Comment by hafeefshaik** [comment]
My apologies, I didn't noticed. Thanks for you quick response.
