### ISSUE TITLE
TSVN Menu Commands not working

### ISSUE THREAD

**Issue by karhak** [sboulema/TSVN#33]
Dear Team,

I have installed TSVN in my vs 2017. Main menu commands not working but "tsvn" submenu commands working.
I have tried to install many versions but result the same.
Please tell me how I can fix this issue.

vs 2017 Pro, version 15.5.7
TSVN 1.9

**Comment by sboulema** [comment]
Hey,

Be sure to use the latest release: [TSVN 4.4.28](https://github.com/sboulema/TSVN/releases/tag/v4.4.28)
And please read the Wiki on your question: [Menu items not working](https://github.com/sboulema/TSVN/wiki/FAQ-Menu-items-not-working)

You probably installed TortoiseSVN without the client tools.

Greetings,

Samir

**Comment by karhak** [comment]
You're absolutely right!
There weren't installed client tools and after adding those TSVN has started working.

Regards,
Karen

**Comment by sboulema** [comment]
Good to hear you got it working!
