### ISSUE TITLE
ReadMe.md has broken links

### ISSUE THREAD

**Issue by RomanBlyshchyk** [sboulema/TSVN#34]
Hey, 
![image](https://user-images.githubusercontent.com/4933359/38755188-cc1dcf54-3f32-11e8-8fe3-7093aa7a44bf.png)

The links under "Features" in the ReadMe file do not show up correctly. 
Once clicked - I get:

> Cannot proxy the given URL

**Comment by sboulema** [comment]
Thanks for notifying me!

Links have been fixed
