### ISSUE TITLE
Rename feature

### ISSUE THREAD

**Issue by LtRAT** [sboulema/TSVN#35]
To rename files in SVN and project simultaneously.
Right now we need to rename it twice, in project and in SVN with restoring it`s old name to do it second time.

**Comment by sboulema** [comment]
This functionality is already available, but you need to enable it.
Read more on the wiki page: [Automatic file operations](https://github.com/sboulema/TSVN/wiki/Automatic-file-operations)

Let me know if that matches your feature request!

**Comment by LtRAT** [comment]
Yes, thanks for wiki page.
