### ISSUE TITLE
tsvn->commit doesn't work properly if accessed from VS Project in Solution explorer

### ISSUE THREAD

**Issue by ash3taunk** [sboulema/TSVN#37]
**Current Behaviour**:
If we access `tsvn->commit` from VS project, it opens commit window only for currently opened file & not for project selected. 
This behaviour steals the purpose of adding tsvn menu on right click of VS projects.

**Expected behaviour**: 
If we access  `tsvn->commit` from VS project in the solution explorer, then it should open commit window for whole project.

**Version using**:
version: 4.4.31
Date installed: 8/17/2018

**Other info**:
Other options of `tsvn`, 
like 
- update, 
- show log, 
- revert, etc 
also works only for current open file.

**Comment by sboulema** [comment]
Thanks for reporting the bug!

Get the new release https://github.com/sboulema/TSVN/releases/tag/v4.4.32 !

**Comment by ash3taunk** [comment]
Thanks buddy :+1:
