### ISSUE TITLE
Repository root folder confusion

### ISSUE THREAD

**Issue by jcugniere** [sboulema/TSVN#39]
Hello,

First, very nice visual studio extension!

One thing I found confusing in one of the new version: when "Repository root folder" is empty, solution wide options such as "Show changes", "Update" or "Commit" do nothing. It would be nice if they displayed a message explaining that "Repository root folder" must be set.

Also I found the name "Repository root folder" confusing. I wasn't sure what to fill, as it sounds a bit like the address of the repository. It also seemed like this setting is global, when in fact it's tied to the current solution.

Maybe the setting should be renamed something like "Working copy root folder for current solution"?

Also, it seems like in some previous version, this setting was automatically determined by your extension? Maybe you could use that logic to set a default value?

**Comment by sboulema** [comment]
Grab the new release! 

Hopefully should clear up some of the confusion :)

**Comment by jcugniere** [comment]
Much clearer, thanks !
