### ISSUE TITLE
Add pending changes window

### ISSUE THREAD

**Issue by sboulema** [sboulema/TSVN#4]
the difference to "Show Changes" is that it's a window that you can dock with other VS windows, and you can click on a file and it will open it in VS. 
you could also revert, commit selected files from there, but what i (and many of my colleagues) miss the most is just being able to easily open the files that i changed without searching for them.
I would expect it to be in a TSVN->Windows menu. 

![unnamed](https://cloud.githubusercontent.com/assets/1820661/15212942/2813f260-1844-11e6-8966-5e5c192b1d98.png)

[Adding a Tool Window](https://msdn.microsoft.com/en-us/library/cc138567.aspx?f=255&MSPPError=-2147217396)

[HOWTO: Create a toolwindow with a ToolWindowPane class in a Visual Studio package](http://www.mztools.com/articles/2015/MZ2015004.aspx)

Requested by: Consuela Stancu Mara

**Comment by sboulema** [comment]
Added with v2.6

**Comment by MarioBalotelli** [comment]
This plugin depends on which version of .net

**Comment by sboulema** [comment]
This plugins uses .net 4.6.1

**Comment by MarioBalotelli** [comment]
thanks
