### ISSUE TITLE
Support for checkpointing (shelve/unshelve)

### ISSUE THREAD

**Issue by joemaffei** [sboulema/TSVN#40]
Checkpointing was recently introduced in SVN 1.11: http://subversion.apache.org/docs/release-notes/1.11.html

TortoiseSVN has made it available through the context menu: https://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-dug-shelving.html

It would be nice to have it in Visual Studio 😄

**Comment by sboulema** [comment]
Shelve:
`/command:shelve /pathfile:"C:\Users\SAMIR~1.BOU\AppData\Local\Temp\svn2221.tmp" /deletepathfile /hwnd:0000000000040468`

Unshelve:
`/command:unshelve /pathfile:"C:\Users\SAMIR~1.BOU\AppData\Local\Temp\svn2C7E.tmp" /deletepathfile /hwnd:0000000000040468`

**Comment by sboulema** [comment]
Thanks for the request!

Grab the new release!
