### ISSUE TITLE
Context Menu Does Not Appear on "Web Site" Project

### ISSUE THREAD

**Issue by b-levitt** [sboulema/TSVN#47]
When I right click a "web site" (no csproj file), I do not get the tsvn menu for that folder:

![image](https://user-images.githubusercontent.com/8228917/51761686-baf2ba00-209b-11e9-9dc2-744204b340e4.png)

Thank you for the work you've done so far with this older project type.

**Comment by sboulema** [comment]
The TSVN menu should be under 'Source Control' :)

![image](https://user-images.githubusercontent.com/1820661/51824699-4ad67500-22e3-11e9-847a-d672ad937bb6.png)
