### ISSUE TITLE
Add mnemonic for Tsvn menu

### ISSUE THREAD

**Issue by bugybunny** [sboulema/TSVN#48]
So I‘m able to hit Alt+Mnemonic to open the menu quickly.

Edit: and also for all commands under this menu. 
Unfortunately, all letters from Tsvn already have a mnemonic in the default VS installation menu. So there’s no unique key that could be used to directly jump to the menu.

**Comment by sboulema** [comment]
Grab the new release! 🚀 

Added keyboard shortcuts are listed here: https://github.com/sboulema/TSVN#keyboard-shortcuts

**Comment by bugybunny** [comment]
This is also great, but not what I wanted. 

I meant the underlined characters in the menu text https://en.wikipedia.org/wiki/Mnemonics_(keyboard).

**Comment by sboulema** [comment]
Ah ok small misunderstandig 😜

Quick investigation didn't reveal a way to add mnemonics in VS extensions. 
Will look further if it is possible to do it!

**Comment by bugybunny** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.menuitem.mnemonic?view=netframework-4.7.2 indicates to me that you just need to add an ampersand & before the letter that should be underlined. When I was looking for that yesterday when I created the issue, you already commented and commited something so I stopped looking^^ Maybe try that with the &.

**Comment by sboulema** [comment]
Extension menu items are not coming from System.Windows.Forms unfortunately.
They are coming from the VSCT file documented here: [VSCT Button Element](https://docs.microsoft.com/en-us/visualstudio/extensibility/button-element?view=vs-2017) which doesn't say anything about mnemonics 😞

**Comment by bugybunny** [comment]
I just had a look at other extensions that I have installed and ReSharper has mnemonics. So it is possible but I don‘t know how.

**Comment by sboulema** [comment]
Sometimes it is so easy... had to use `&amp;` in the .vsct file 😁

Grab the new release! 🚀

**Comment by bugybunny** [comment]
Ah :D Thanks a lot for the quick implementation!

**Comment by bugybunny** [comment]
I just added a mnemonic for all top level Tsvn menus. I just changed the file but didn‘t build it, hopefully it doesn‘t break anything.
