### ISSUE TITLE
How Pending Changes window works?

### ISSUE THREAD

**Issue by gigios** [sboulema/TSVN#53]
Don't hate me 😄 , I want to replace the 'un-working' AnkhSVN with your extension that has more possibilities, and I hope, it's an active project.

I'm searching a way to understand what are the changed files (because currently there aren't overlay icons).
I have found the TSVN Pending Changes window but it's not clear how works.

First I have a problem with the icons, I'm using the Dark color theme and the icons in the window are black, not very visible.
Second, I have changed some files and all the AssemblyInfo.cs with the new version number (AssemblyInfo of more projects in the same solution).
Theoretically the AssemblyInfo.cs file is under the Properties folder of each project, but in the Pending Changes window I don't understand the visualization, seems that the treeview is not correct.
![immagine](https://user-images.githubusercontent.com/8749627/55534937-f15d3e80-56b5-11e9-8c6d-57581afc80ba.png)

For example, the xxxCommunication project seems without changes, but there is a Properties folder, and relative AssemblyInfo, at the same level (seems that the Properties folder is a different Project).
At the same level of the Communication there is also an additional AssemblyInfo.
Same problems for all the other projects, where, theoretically, each project has its modified AssemblyInfo file.

**Comment by sboulema** [comment]
I don't hate you!

Thanks for reporting, will look into fixing these.
And yes TSVN is an active project, but it is a hobby project, so I can only work on it in the spare hours ;)

**Comment by sboulema** [comment]
Progress is being made...

![image](https://user-images.githubusercontent.com/1820661/55626797-cacdff00-57ac-11e9-8940-b138d2df1cbf.png)

**Comment by sboulema** [comment]
Can you please send me the output of `svn status` when ran from a command prompt in that directory?

You can send it to vsix@sboulema.nl, and of course everything will be treated as confidential.

**Comment by sboulema** [comment]
Grab the new release ([v4.8.51](https://github.com/sboulema/TSVN/releases/tag/v4.8.51))! :rocket:

**Comment by gigios** [comment]
Perfect, now seems correct!
Thanks
