### ISSUE TITLE
TSVN in Visual Studio 2019 not showing Pending Changes

### ISSUE THREAD

**Issue by pangal** [sboulema/TSVN#55]
I have installed TSVN (by using the 'Manage Extensions' menu) in Microsoft Visual Studio 2019 Community Edition. The menu 'Source control > Tsvn' appears on every project item with all choices. The problem is that the window 'TSVN Pending Changes' does not show changes to project items neither with the Refresh button nor automatically. Do you have any idea what's wrong? I have reinstalled the TSVN extension with administrative rights but nothing changed.
Thanks a lot.

**Comment by sboulema** [comment]
Hmmm that is strange, it works for me:
![image](https://user-images.githubusercontent.com/1820661/59338017-e6500b80-8d01-11e9-822e-4d5cfae94091.png)

Have you checked that the client tools are installed:
https://github.com/sboulema/TSVN/wiki/Menu-items-not-working

**Comment by pangal** [comment]
It  works!

Thanks a lot.

 

Γαλάνης Παναγιώτης

Μηχανικός Λογισμικού

 <mailto:galanis.p@epafos.gr> galanis.p@epafos.gr

  _____  

ΕΠΑΦΟΣ ΣΥΣΤΗΜΑΤΑ ΠΛΗΡΟΦΟΡΙΚΗΣ

Λ. Ελευθερίου Βενιζέλου 46 - 48 & Κανακίδη 1, 176 76 Καλλιθέα

Τel: 210 699 0401 Fax: 210 699 0441 Web:  <http://www.epafos.gr> http://www.epafos.gr 

Social:  <http://www.facebook.com/epafos> Facebook //  <http://www.twitter.com/epafos> Twitter //  <https://www.youtube.com/channel/UCmbUyuLmKiF75xyNAT6tyVA> Youtube //  <http://plus.google.com/+epafos> Google+ //  <https://www.google.com/maps/place/%CE%95%CE%A0%CE%91%CE%A6%CE%9F%CE%A3+%CE%A3%CE%A5%CE%A3%CE%A4%CE%97%CE%9C%CE%91%CE%A4%CE%91+%CE%A0%CE%9B%CE%97%CE%A1%CE%9F%CE%A6%CE%9F%CE%A1%CE%99%CE%9A%CE%97%CE%A3+%CE%95.%CE%A0.%CE%95./@37.962533,23.712036,17z/data=!3m1!4b1!4m2!3m1!1s0x14a19804567d43e9:0x3b48e7871e5da7bf> GoogleMaps 

ΑΠΟΠΟΙΗΣΗ ΕΥΘΥΝΗΣ: Αυτό το e-mail και οι τυχόν επισυνάψεις του είναι εμπιστευτικά και συνεπώς προστατεύονται από το Νόμο. Εάν δεν είστε ο παραλήπτης στον οποίο απευθύνεται, σας ενημερώνουμε ότι οποιαδήποτε αποκάλυψη, αναπαραγωγή, διανομή ή άλλη χρήση απαγορεύεται. Εάν παραλάβατε το συγκεκριμένο εκ παραδρομής, παρακαλούμε επικοινωνήστε με τον αποστολέα και διαγράψτε το από τους υπολογιστές σας.

**Comment by pangal** [comment]
It is working after I changed the TortoiseSVN setup as mentioned in your article.
Thank you very much!

**Comment by Luich** [comment]
> Hmmm that is strange, it works for me: ![image](https://user-images.githubusercontent.com/1820661/59338017-e6500b80-8d01-11e9-822e-4d5cfae94091.png)
> 
> Have you checked that the client tools are installed: https://github.com/sboulema/TSVN/wiki/Menu-items-not-working

I am having the same problem but this link is not working anymore

**Comment by sboulema** [comment]
Did you install TortoiseSVN with "client tools"?

The wiki is located here: https://github.com/sboulema/TSVN/wiki/TSVN-not-working#problem

See the screenshot with the installation option that must be checked.

**Comment by Luich** [comment]
Apparently I needed to check that option.
Thank you!
