### ISSUE TITLE
TSVN context menu missing from cshtml editor

### ISSUE THREAD

**Issue by 0x15e** [sboulema/TSVN#57]
I'm currently seeing this in VS2019 but I remember it was going on in 2017 as well (just never reported it).

In most editors, the text area's context menu as a TSVN section that includes useful things like Show Log, Blame, Revert, etc. (the standard TSVN context menu). Unfortunately, that doesn't appear in the editor for cshtml files (Razor views).

Would it be possible to add this? Right now I can get to it by using the Extensions -> TSVN -> TSVN drop-down menus but it sure would be convenient to have it in the context menu for all text editors.

Hopefully it's just a matter of adding some sort of registration for it. The editors typically used for cshtml files are either HTML Editor or HTML Editor with Encoding.

Thank you!

**Comment by 0x15e** [comment]
I also noticed this happens in the SCSS Editor (and SCSS Editor with Encoding) as well.

**Comment by sboulema** [comment]
Grab the new release! :rocket:

[v4.8.52](https://github.com/sboulema/TSVN/releases/tag/v4.8.52)

**Comment by 0x15e** [comment]
Awesome! Thank you!
