### ISSUE TITLE
Error "Unable to determine the solution directory location"

### ISSUE THREAD

**Issue by sgavriel** [sboulema/TSVN#59]
I'm using VS 2019 version 16.2.3 and the latest TSVN ver. 4.8.52
Since the last VS2019 update, the TSVN has the error:
"Unable to determine the solution directory location. Please manually set the directory location in the settings".
But I can not find a place to set the directory.
This error appears in every action I'm clicking on at the TSVN. It appears also when the VS2019 has no open project or solution.

How can I fix that?

![Error](https://user-images.githubusercontent.com/19684799/63427577-1e6c7c80-c41e-11e9-8616-9f1fd3bfc755.PNG)
![VS2019 Info](https://user-images.githubusercontent.com/19684799/63427592-275d4e00-c41e-11e9-8e32-889e410846de.PNG)

**Comment by sboulema** [comment]
You should be able to set the path in the settings window: TSVN -> Windows -> Options

Will look into fixing the bug. Sounds like the new changes in how the extension is loaded async

**Comment by sboulema** [comment]
Also have you checked that the TortoiseSVN client tools are installed:

https://github.com/sboulema/TSVN/wiki/TSVN-not-working

**Comment by sgavriel** [comment]
The client tools was installed.
I could not find how path.
But I removed the TSVN and reinstalled it. Now it works fine :-)

**Comment by sboulema** [comment]
Great to hear!
