### ISSUE TITLE
Detection of Working copy root path fails with non-english language settings

### ISSUE THREAD

**Issue by amanjitgill** [sboulema/TSVN#64]
Hi, 

First of all: Nice tool, like it!..  

On "german svn client installations, where the svn client language has also been set to german (quite common) the working copy root path won't be detected 

the string comparison with the hardcoded string fails... https://github.com/sboulema/TSVN/blob/03ef4b7f8b1f646c99427c51fec3788974ab69ff/TSVN/Helpers/CommandHelper.cs#L128

Because of i18n, the svn status command returns a different string than "Working Copy Root Path", for german it returns ""Wurzelpfad der Arbeitskopie, see the i18n file: "http://svn.apache.org/repos/asf/subversion/branches/1.9.x/subversion/po/de.po) 

Maybe you should do something like 

` svn info --show-item wc-root`

Cheers

**Comment by amanjitgill** [comment]
ping :-)

**Comment by sboulema** [comment]
pong :-)

Grab the new release 🚀

**Comment by amanjitgill** [comment]
Thanks a lot, gonna check it out in the near future
