### ISSUE TITLE
VS 2019 "The Tvsc package did not load correctly" for 5.0.61

### ISSUE THREAD

**Issue by chk2902** [sboulema/TSVN#66]
The extension was auto-updated today, and I cannot use it any more in my Visual Studio.

Error is

`SetSite failed for package [TsvnPackage]Source: 'Microsoft.VisualStudio.Validation' Description: Cannot find an instance of the EnvDTE80.DTE2 service.`

**Comment by chk2902** [comment]
... nearly a duplicate of #56, but no "Crash" here. It just does not work.

**Comment by sboulema** [comment]
Thanks for reporting!

Grab the new release 🚀

**Comment by chk2902** [comment]
👍
