### ISSUE TITLE
Crash on use Commit menu

### ISSUE THREAD

**Issue by dmitryvhf** [sboulema/TSVN#69]
Click to menu "Commit" crash Visual Studio. Can't find crash logs.

Simulation:
* Open VS without project
* Click to menu "Commit"
* Random result:
  * showed dialog "Missing Working Copy Root Path". "OK". No crash. If just launched VS.
  * showed dialog "Missing Working Copy Root Path". "OK". Crash. Time passed after launch VS.
  * Сrash

Visual Studio 2019, Version 5.0.707

**Comment by sboulema** [comment]
Should be fixed in the new release 🚀 
Be sure to get the right version because I have splitted the extension in a VS2022 version and a VS2019 and prior version.

Will be on holiday from tomorrow, so new builds will have to wait for a bit 🌞

**Comment by dmitryvhf** [comment]
Thanks, fixed. Version 5.1.711

**Comment by dmitryvhf** [comment]
Visual Studio 2019, "TSVN 2019", Version 5.1.729 - crash.

Version 5.1.711 VSIX is not available for download. :( Cant use now. Removed yet
