### ISSUE TITLE
TSVN errors when working on a solution that does not use SVN

### ISSUE THREAD

**Issue by wazzamatazz** [sboulema/TSVN#70]
TSVN Extension Version: 5.0.707
Tortoise SVN Version: 1.14.1

Some projects that I work on use SVN for source control, and others use Git.

Since updating to TSVN 5.0.686, I get TortoiseSVN error dialogs popping up in Visual Studio whenever I work on a solution that uses Git and I perform an action like adding or removing a file to a project:

```
Subversion reported an error:

'<PATH OF FILE> is not a working copy'
```

I still see this error in TSVN 5.0.707. I also updated to Tortoise SVN 1.14.1 recently, so this may also be the culprit. Disabling the extension while working on Git-based projects is a workaround, but it's a bit of a pain since I frequently have to work on both types of projects at the same time.

**Comment by Philippe91** [comment]
I confirm. More exactly, opening any file that is not part of the SVN repository causes an error box to popup (eg. just openeing a header file from a third-party library).  Workflow killer :(
I have to revert to version 4.

**Comment by sboulema** [comment]
Should be fixed in the new release 🚀 
Be sure to get the right version because I have splitted the extension in a VS2022 version and a VS2019 and prior version.

Will be on holiday from tomorrow, so new builds will have to wait for a bit 🌞

**Comment by Philippe91** [comment]
Fixed confirmed :) Have great vacations :)

**Comment by wazzamatazz** [comment]
Fixed for me too!
