### ISSUE TITLE
Crash on use Commit menu (VS2019, 5.1.729)

### ISSUE THREAD

**Issue by dmitryvhf** [sboulema/TSVN#71]
Visual Studio 2019, "TSVN 2019", Version 5.1.729 - crash.
#69 again

Version 5.1.711 VSIX is not available for download. :( Cant use now. Removed yet

**Comment by sboulema** [comment]
Oh no, seems like a difficult bug to kill!

Try the new release (5.1.731)

**Comment by dmitryvhf** [comment]
Thanks for fast support. 👍  I glad to help you to improve app. ;)

Simce like good. "Pending Changes", "Commit", "Update", "Shelve" etc.
But... has been randomly crash. One time - crash on project loading; second - single file (right mouse menu) Commit. Now is not reproductive yet. I will be continue checking it.

Detail: "Visual Studio 2019" (16.11.0 Preview 3.0). Maybe **Preview** is problem? :)

**Comment by sboulema** [comment]
Glad to hear it is at least partly fixed :P

Sounds like a timing/async issue, will do some further investigation.

Preview shouldn't be a problem, I am developing TSVN using VS 2022 Preview...

**Comment by dmitryvhf** [comment]
Please, release 5.1.711 VSIX for manualy downloading. This stable build.

**Comment by sboulema** [comment]
https://github.com/sboulema/TSVN/releases/tag/v5.1.711

**Comment by mvdhorst** [comment]
> Oh no, seems like a difficult bug to kill!
> 
> Try the new release (5.1.731)

too bad, this doesn't work either.

**Comment by sboulema** [comment]
Not giving up! Please try the new release (5.1.734)

**Comment by dmitryvhf** [comment]
> Please try the new release (5.1.734)
Sorry, but crash again.
Open VS. Open project. Click "Commit", (all ok), close window.
Change code. Click "Commit". Hold, crash.
Reopen VS. Open project. Click "Commit". Hold, crash.

**Comment by sboulema** [comment]
:(

Thanks for testing these builds, give this release a try please (5.1.735)

**Comment by mvdhorst** [comment]
> :(
> 
> Thanks for testing these builds, give this release a try please (5.1.735)

Seems to work now! thanks for the quick response!

**Comment by dmitryvhf** [comment]
> > :(
> > Thanks for testing these builds, give this release a try please (5.1.735)
> 
> Seems to work now! thanks for the quick response!

Confirm! "Click test is succesfully" :D

**Comment by dmitryvhf** [comment]
v5.1.735 is stable. All features works.
