### ISSUE TITLE
Could not load file or assembly Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0 or one of its dependencies

### ISSUE THREAD

**Issue by EdDibbs** [sboulema/TSVN#72]
I use the TSVN extension with VS2017 and as of v5.1.731, the extension fails to start. Opening up the ActivityLog.xml file shows the following error:

> CreateInstance failed for package [TsvnPackage]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The located assembly&apos;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) System.IO.FileLoadException: Could not load file or assembly &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. 
> 
> The located assembly&apos;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) File name: &apos;Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type) at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase) at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo) at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName) WRN: Assembly binding logging is turned OFF. 
> 
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1. Note: There is some performance penalty associated with assembly bind failure logging. To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Reverting to v5.1.731 fixes this issue for me.

**Comment by sboulema** [comment]
Please try the new release (5.1.734)

**Comment by EdDibbs** [comment]
Tested with 5.1.735 and the issue appears resolved. Thanks!
