### ISSUE TITLE
Pending changes window doesn't support dark theme

### ISSUE THREAD

**Issue by sh4nji** [sboulema/TSVN#8]
Black text on dark grey background is very hard to read :) In our team of 14 at least 50% use the dark theme.

**Comment by sboulema** [comment]
Completely forgot about the black theme... Good suggestion!
Will look into it.

**Comment by sboulema** [comment]
Save some documentation for the future:
http://igrali.com/2012/01/21/make-image-visible-on-both-white-and-black-background-theme-color-on-windows-phone/

**Comment by sboulema** [comment]
Should be fixed with the newly released 2.8 version!
